version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: satellite-personal-node_web_1
      APP_PORT: 3000
      PROXY_AUTH_ADD: "false"

  web:
    image: ghcr.io/satellite-earth/personal-node:0.3
    restart: on-failure
    stop_grace_period: 1m
    init: true
    volumes:
      - ${APP_DATA_DIR}/data:/data
    environment:
      DATA_PATH: /data
      REDIRECT_APP_URL: https://app.satellite.earth/
