version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: satellite-personal-node_web_1
      APP_PORT: 3000
      PROXY_AUTH_ADD: "false"

  web:
    image: ghcr.io/satellite-earth/personal-node:0.3
    restart: on-failure
    stop_grace_period: 1m
    init: true
    volumes:
      - ${APP_DATA_DIR}/data:/data
    environment:
      DATA_PATH: /data
      REDIRECT_APP_URL: https://app.satellite.earth/
      TOR_ADDRESS: ${APP_HIDDEN_SERVICE}
      TOR_PROXY_TYPE: "SOCKS5"
      TOR_PROXY: "$TOR_PROXY_IP:$TOR_PROXY_PORT"
      I2P_SAM_ADDRESS: "i2pd_daemon:7656"
      I2P_PROXY: "i2pd_daemon:4447"
      I2P_PROXY_TYPE: "SOCKS5"

  i2pd_daemon:
    image: purplei2p/i2pd:release-2.44.0@sha256:d154a599793c393cf9c91f8549ba7ece0bb40e5728e1813aa6dd4c210aa606f6
    user: "root"
    command: --sam.enabled=true --sam.address=0.0.0.0 --sam.port=7656 i2pd --socks.enabled=true --socks.address=0.0.0.0 --socks.port=4447 --loglevel=error
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data/i2pd:/home/i2pd/data
